- name: Copy sample.jar to remote vm
  copy: src=/root/.jenkins/workspace/pipeline-junit/target/sample.jar dest=~/  mode=0755

- name: Get running sample.jar
  shell: "ps -ef | grep -v grep | grep -w sample.jar | awk '{print $2}'"
  register: running_processes

- name: Kill running sample.jar
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: killed_processes

- name: Force kill stuck sample.jar
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

- name: Sleep 3s
  shell: sleep 3s
